plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/0x1ad2/Projects/property-cleaning-service-bv/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/0x1ad2/Projects/property-cleaning-service-bv"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]