import type { Product } from "./types";

const IMG = "/images/optimized";

export const products: Product[] = [
  // --- Schoonmaakmiddelen ---
  {
    id: "p-001",
    name: "Ultra-Pure Allesreiniger",
    category: "Schoonmaakmiddelen",
    price: 12.95,
    currency: "EUR",
    rating: 4.8,
    tags: ["allesreiniger", "professioneel", "bestseller"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (2).webp`,
    description:
      "Krachtige allesreiniger op basis van biologisch afbreekbare ingrediënten. Geschikt voor alle harde oppervlakken in kantoren, zorginstellingen en industriële omgevingen. Verwijdert hardnekkig vuil zonder strepen achter te laten.",
    shortDescription: "Professionele biologisch afbreekbare allesreiniger",
    volume: "1 Liter",
    variants: [
      { id: "v-001a", name: "1 Liter", price: 12.95 },
      { id: "v-001b", name: "5 Liter", price: 49.95 },
    ],
    createdAt: "2025-12-01",
  },
  {
    id: "p-002",
    name: "Glasreiniger Pro",
    category: "Schoonmaakmiddelen",
    price: 9.95,
    currency: "EUR",
    rating: 4.6,
    tags: ["glasreiniger", "streepvrij", "professioneel"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (3).webp`,
    description:
      "Streepvrije glasreiniger voor een sprankelend schone afwerking op ramen, spiegels en glazen oppervlakken. Sneldrogend en geschikt voor dagelijks gebruik in commerciële omgevingen.",
    shortDescription: "Streepvrije professionele glasreiniger",
    volume: "750 ml",
    createdAt: "2025-11-15",
  },
  {
    id: "p-003",
    name: "Vloerreiniger Industrial",
    category: "Schoonmaakmiddelen",
    price: 18.5,
    currency: "EUR",
    rating: 4.7,
    tags: ["vloerreiniger", "industrieel", "professioneel"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board.webp`,
    description:
      "Industrieel sterke vloerreiniger voor harde vloeren zoals tegels, beton en vinyl. Verwijdert olie, vet en hardnekkige vlekken. Laat een frisse geur achter en beschermt de vloer.",
    shortDescription: "Industrieel sterke vloerreiniger voor harde vloeren",
    volume: "5 Liter",
    variants: [
      { id: "v-003a", name: "5 Liter", price: 18.5 },
      { id: "v-003b", name: "10 Liter", price: 32.95 },
    ],
    createdAt: "2026-01-10",
  },
  {
    id: "p-004",
    name: "Floor Cleaner & Polish",
    category: "Schoonmaakmiddelen",
    price: 14.75,
    currency: "EUR",
    rating: 4.5,
    tags: ["vloerreiniger", "polish", "glans"],
    inStock: true,
    image: `${IMG}/Cleaning Products.webp`,
    description:
      "Twee-in-één vloerreiniger en polish die tegelijkertijd reinigt en een beschermende glanslaag aanbrengt. Ideaal voor kantoorvloeren en ontvangstruimten.",
    shortDescription: "Reinigt en geeft glans in één behandeling",
    volume: "1 Liter",
    createdAt: "2026-02-01",
  },
  // --- Microvezel ---
  {
    id: "p-005",
    name: "Premium Microvezeldoek Set (10 stuks)",
    category: "Microvezel",
    price: 24.95,
    currency: "EUR",
    rating: 4.9,
    tags: ["microvezeldoek", "premium", "bestseller", "set"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (1).webp`,
    description:
      "Set van 10 hoogwaardige microvezeldoeken in diverse kleuren voor kleurcodering per ruimte. Extra dik (340 gsm) voor optimale opname van vuil en vocht. Wasbaar tot 90°C.",
    shortDescription: "10-delige premium microvezeldoek set",
    createdAt: "2025-10-20",
  },
  {
    id: "p-006",
    name: "Glasdoek Microvezel (5 stuks)",
    category: "Microvezel",
    price: 15.5,
    currency: "EUR",
    rating: 4.7,
    tags: ["microvezeldoek", "glasdoek", "streepvrij"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (4).webp`,
    description:
      "Speciaal geweven microvezeldoeken voor streepvrije glasreiniging. Ultra-fijne vezels vangen stofdeeltjes op zonder krassen. Set van 5 stuks.",
    shortDescription: "Streepvrije glasdoeken van microvezel",
    createdAt: "2025-11-05",
  },
  {
    id: "p-007",
    name: "Stofdoek XXL Microvezel",
    category: "Microvezel",
    price: 8.95,
    currency: "EUR",
    rating: 4.4,
    tags: ["microvezeldoek", "stof", "xxl"],
    inStock: false,
    image: `${IMG}/Property cleaning service - illustrationImage.webp`,
    description:
      "Extra groot microvezeldoek (60x40 cm) speciaal ontworpen voor het afstoffen van grote oppervlakken. Elektrostatische werking vangt stof op zonder dat het verspreidt.",
    shortDescription: "Extra groot microvezeldoek voor stofverwijdering",
    createdAt: "2025-09-12",
  },
  {
    id: "p-008",
    name: "Vloerdoek Microvezel (3 stuks)",
    category: "Microvezel",
    price: 19.95,
    currency: "EUR",
    rating: 4.6,
    tags: ["microvezeldoek", "vloerdoek", "wasbaar"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (2).webp`,
    description:
      "Robuuste microvezelvloerdoeken voor dagelijks nat en droog dweilen. Passen op standaard 40cm vlakmoppen. Wasbaar tot 95°C voor hygienisch hergebruik.",
    shortDescription: "Robuuste vloerdoeken voor professioneel gebruik",
    createdAt: "2026-01-25",
  },
  // --- Moppensets ---
  {
    id: "p-009",
    name: "Professionele Vlakmop Set",
    category: "Moppensets",
    price: 45.0,
    currency: "EUR",
    rating: 4.8,
    tags: ["vlakmop", "professioneel", "set", "bestseller"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (1).webp`,
    description:
      "Complete professionele vlakmop set inclusief aluminium steel (140 cm), klapsysteem en 3 microvezelmoppen. Ergonomisch ontwerp voor vermoeiend dagelijks gebruik. Geschikt voor alle harde vloeren.",
    shortDescription: "Complete vlakmop set met 3 microvezelmoppen",
    createdAt: "2025-08-15",
  },
  {
    id: "p-010",
    name: "Spaanse Mop Industrieel",
    category: "Moppensets",
    price: 32.5,
    currency: "EUR",
    rating: 4.3,
    tags: ["spaanse mop", "industrieel", "groot"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board.webp`,
    description:
      "Industriële Spaanse mop met versterkte steel en extra groot mopgedeelte voor het reinigen van magazijnen, werkplaatsen en grote commerciële ruimten.",
    shortDescription: "Industriële mop voor grote oppervlakken",
    createdAt: "2025-10-01",
  },
  {
    id: "p-011",
    name: "Telescopische Mopsteel",
    category: "Moppensets",
    price: 22.95,
    currency: "EUR",
    rating: 4.5,
    tags: ["mopsteel", "telescopisch", "aluminium"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (3).webp`,
    description:
      "Verstelbare aluminium mopsteel van 100 tot 180 cm. Lichtgewicht maar stevig, geschikt voor alle vlakmopsystemen. Ergonomische grip voor langdurig gebruik.",
    shortDescription: "Verstelbare aluminium mopsteel 100–180 cm",
    createdAt: "2026-02-15",
  },
  {
    id: "p-012",
    name: "Vervangmoppen Set (5 stuks)",
    category: "Moppensets",
    price: 27.5,
    currency: "EUR",
    rating: 4.6,
    tags: ["vervangmoppen", "microvezel", "set"],
    inStock: false,
    image: `${IMG}/Property cleaning service - AI Image board (4).webp`,
    description:
      "Set van 5 vervangmoppen van hoogwaardige microvezel. Geschikt voor standaard 40 cm vlakmoppen. Wasbaar tot 95°C, behoudt absorptie na 500+ wasbeurten.",
    shortDescription: "5 vervangmoppen voor standaard vlakmoppen",
    createdAt: "2025-12-20",
  },
  // --- Emmers & Toebehoren ---
  {
    id: "p-013",
    name: "Mopemmer met Wringer 25L",
    category: "Emmers & Toebehoren",
    price: 38.95,
    currency: "EUR",
    rating: 4.7,
    tags: ["emmer", "wringer", "professioneel"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (2).webp`,
    description:
      "Professionele 25-liter mopemmer met ingebouwde wringer en verrijdbaar onderstel. Stabiel ontwerp met gietrand en maataanduiding. Ideaal voor groot oppervlak reiniging.",
    shortDescription: "25L professionele mopemmer met wringer",
    createdAt: "2025-11-20",
  },
  {
    id: "p-014",
    name: "Schoonmaakwagen Compleet",
    category: "Emmers & Toebehoren",
    price: 189.0,
    currency: "EUR",
    rating: 4.9,
    tags: ["schoonmaakwagen", "compleet", "professioneel", "bestseller"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (1).webp`,
    description:
      "Complete professionele schoonmaakwagen met dubbele emmer (2x 15L), mopwringer, afvalzak houder, opbergvakken voor schoonmaakmiddelen en bezem/mop houders. Robuuste wielen voor soepel manoeuvreren.",
    shortDescription: "Complete professionele schoonmaakwagen",
    createdAt: "2025-07-10",
  },
  {
    id: "p-015",
    name: "Sprayfles Professioneel (3 stuks)",
    category: "Emmers & Toebehoren",
    price: 11.95,
    currency: "EUR",
    rating: 4.4,
    tags: ["sprayfles", "hervulbaar", "set"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board.webp`,
    description:
      "Set van 3 professionele sprayflessen van 750 ml met verstelbare sproeikop (mist/straal). Chemisch bestendige uitvoering met maataanduiding en etiketruimte voor kleurcodering.",
    shortDescription: "3 hervulbare professionele sprayflessen",
    createdAt: "2026-01-05",
  },
  {
    id: "p-016",
    name: "Doseerpomp 5L",
    category: "Emmers & Toebehoren",
    price: 6.95,
    currency: "EUR",
    rating: 4.2,
    tags: ["doseerpomp", "5 liter", "toebehoren"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (3).webp`,
    description:
      "Universele doseerpomp geschikt voor 5-liter jerrycans. Exacte dosering bespaart schoonmaakmiddel en voorkomt morsen. Eenvoudig te bevestigen.",
    shortDescription: "Universele doseerpomp voor 5L jerrycans",
    createdAt: "2025-12-10",
  },
  // --- Desinfectie ---
  {
    id: "p-017",
    name: "Oppervlakte Desinfectant Pro",
    category: "Desinfectie",
    price: 16.95,
    currency: "EUR",
    rating: 4.8,
    tags: ["desinfectie", "oppervlakte", "professioneel", "bestseller"],
    inStock: true,
    image: `${IMG}/Property cleaning service - illustrationImage.webp`,
    description:
      "Professioneel oppervlakte desinfectiemiddel dat 99,99% van bacteriën en virussen elimineert. Geschikt voor zorginstellingen, kantoren en horeca. Alcohol-gebaseerd, sneldrogend.",
    shortDescription: "Elimineert 99,99% van bacteriën en virussen",
    volume: "1 Liter",
    variants: [
      { id: "v-017a", name: "1 Liter spray", price: 16.95 },
      { id: "v-017b", name: "5 Liter navul", price: 59.95 },
    ],
    createdAt: "2025-09-25",
  },
  {
    id: "p-018",
    name: "Handdesinfectie Gel",
    category: "Desinfectie",
    price: 7.5,
    currency: "EUR",
    rating: 4.5,
    tags: ["handdesinfectie", "gel", "hygiëne"],
    inStock: true,
    image: `${IMG}/Cleaning Products.webp`,
    description:
      "Handdesinfectie gel met 70% alcohol voor optimale handhygiëne. Snel absorberend, niet plakkerig. Bevat verzorgende aloë vera. Geschikt voor frequente toepassing.",
    shortDescription: "Handdesinfectie gel met 70% alcohol en aloë vera",
    volume: "500 ml",
    createdAt: "2026-02-20",
  },
  {
    id: "p-019",
    name: "Sanitair Desinfectant",
    category: "Desinfectie",
    price: 13.5,
    currency: "EUR",
    rating: 4.6,
    tags: ["sanitair", "desinfectie", "toilet"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (2).webp`,
    description:
      "Krachtige sanitair desinfectant voor toiletten, wastafels en doucheruimten. Verwijdert kalkaanslag en zeepresidu terwijl het desinfecteert. Aangename frisse geur.",
    shortDescription: "Krachtige sanitair reiniger en desinfectant",
    volume: "1 Liter",
    createdAt: "2025-10-15",
  },
  {
    id: "p-020",
    name: "Desinfectiedoekjes (200 stuks)",
    category: "Desinfectie",
    price: 22.95,
    currency: "EUR",
    rating: 4.7,
    tags: ["desinfectiedoekjes", "handig", "hygiëne"],
    inStock: false,
    image: `${IMG}/Property cleaning service - AI Image board (4).webp`,
    description:
      "Grote dispenserdoos met 200 desinfectiedoekjes voor snelle reiniging van bureaus, telefoons, deurklinken en andere contactpunten. Effectief tegen bacteriën en virussen.",
    shortDescription: "200 desinfectiedoekjes in dispenserdoos",
    createdAt: "2025-11-28",
  },
  // --- Beschermingsmiddelen ---
  {
    id: "p-021",
    name: "Nitril Handschoenen (100 stuks)",
    category: "Beschermingsmiddelen",
    price: 14.95,
    currency: "EUR",
    rating: 4.6,
    tags: ["handschoenen", "nitril", "wegwerp"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (3).webp`,
    description:
      "Poedervrije nitril handschoenen in dispenserdoos van 100 stuks. Chemisch bestendig, latex-vrij en geschikt voor mensen met een latexallergie. Beschikbaar in maten S t/m XL.",
    shortDescription: "100 poedervrije nitril handschoenen",
    variants: [
      { id: "v-021a", name: "Maat S", price: 14.95 },
      { id: "v-021b", name: "Maat M", price: 14.95 },
      { id: "v-021c", name: "Maat L", price: 14.95 },
      { id: "v-021d", name: "Maat XL", price: 14.95 },
    ],
    createdAt: "2026-01-15",
  },
  {
    id: "p-022",
    name: "Veiligheidsbril Transparant",
    category: "Beschermingsmiddelen",
    price: 8.5,
    currency: "EUR",
    rating: 4.3,
    tags: ["veiligheidsbril", "oogbescherming", "transparant"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board.webp`,
    description:
      "Lichtgewicht veiligheidsbril met anti-kras en anti-condens coating. Wraparound ontwerp biedt 180° bescherming. Comfortabele pasvorm, geschikt voor brildragers.",
    shortDescription: "Lichtgewicht veiligheidsbril met anti-condens",
    createdAt: "2025-08-20",
  },
  {
    id: "p-023",
    name: "Schort Waterdicht",
    category: "Beschermingsmiddelen",
    price: 12.5,
    currency: "EUR",
    rating: 4.4,
    tags: ["schort", "waterdicht", "bescherming"],
    inStock: true,
    image: `${IMG}/Property cleaning service - illustrationImage.webp`,
    description:
      "Waterdicht polyester/PVC schort met verstelbare nekband en tailleband. Beschermt kleding bij nat werk en het werken met schoonmaakmiddelen. Eenvoudig af te nemen.",
    shortDescription: "Waterdicht schort met verstelbare banden",
    createdAt: "2026-02-05",
  },
  {
    id: "p-024",
    name: "Kniebeschermers Pro",
    category: "Beschermingsmiddelen",
    price: 19.95,
    currency: "EUR",
    rating: 4.5,
    tags: ["kniebeschermers", "ergonomisch", "comfort"],
    inStock: true,
    image: `${IMG}/Property cleaning service - AI Image board (1).webp`,
    description:
      "Ergonomische kniebeschermers met gel-vulling voor maximaal comfort bij knielend werk. Verstelbare elastische banden en anti-slip oppervlak. Geschikt voor langdurig gebruik.",
    shortDescription: "Ergonomische gel kniebeschermers",
    createdAt: "2025-12-28",
  },
];

export const ALL_TAGS = Array.from(
  new Set(products.flatMap((p) => p.tags)),
).sort();

export const PRICE_MIN = 0;
export const PRICE_MAX =
  Math.ceil(Math.max(...products.map((p) => p.price)) / 10) * 10;

export const DELIVERY_OPTIONS = [
  {
    option: "standard" as const,
    cost: 6.95,
    label: "Standaard Bezorging",
    estimate: "3–5 werkdagen",
  },
  {
    option: "express" as const,
    cost: 14.95,
    label: "Express Bezorging",
    estimate: "1–2 werkdagen",
  },
];

export const TAX_RATE = 0.21;
